# Generated by Django 3.2.9 on 2021-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/%y', verbose_name=''),
        ),
    ]
