# Generated by Django 3.2.8 on 2021-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
