# Generated by Django 3.2.8 on 2021-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_id',
            field=models.IntegerField(default=-1),
        ),
    ]
